source "https://github.com/CocoaPods/Specs.git"
source "https://github.com/TouchInstinct/Podspecs.git"

abstract_target 'LeadKitAdditions' do
  pod 'KeychainAccess', '3.1.0'
  pod 'IDZSwiftCommonCrypto'
  pod 'InputMask', '3.0.0'
  pod 'SwiftValidator', '4.0.2'

  inhibit_all_warnings!

  target 'LeadKitAdditions iOS' do
    platform :ios, '13.0'

    use_frameworks!

    pod 'LeadKit', :git => 'https://github.com/procommerz/LeadKit', :branch => 'farmyBranch2021'
  end

  target 'LeadKitAdditions iOS Extensions' do
    platform :ios, '13.0'

    use_frameworks!

    pod 'LeadKit', :git => 'https://github.com/procommerz/LeadKit', :branch => 'farmyBranch2021'
  end
end

# If you have slow HDD
ENV['COCOAPODS_DISABLE_STATS'] = "true"

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf'
          config.build_settings['SWIFT_VERSION'] = '5.0'
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
end